version: 2.1

orbs:
  win: circleci/windows@5.0.0 

jobs:
  build:
    executor: win/server-2022
  hello-job:
    executor:
      name: win/default # executor type
      size: "medium"

    steps:
      - checkout
      - run: Write-Host 'Hello, Windows'

workflows:
  my-workflow:
    jobs:
      - hello-job
